name: Check dependencies for security vulnerabilities

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Run OWASP Dependency-Check
      run: |
        docker run --rm -v $(pwd):/code owasp/dependency-check --scan /code


    - name: Run bandit on Superset code
      run: |
        pip install bandit 
        bandit -r ${{ github.workspace }}/superset 

    - name: Upload Bandit report
      uses: actions/upload-artifact@v2
      with:
        name: bandit-report
        path: /src/./dependency-check-report.html

   


