name: Check dependencies for security vulnerabilities

on:
  push:
    branches:
      - master
  # pull_request:
  #   branches:
  #     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run OWASP Dependency-Check
        run: |
          docker run   -v $(pwd) owasp/dependency-check --scan  $(pwd)    --project "$DC_PROJECT" \
          --out /report --format HTML
          ls -la $(pwd)


      - name: Upload dependencies report
        uses: actions/upload-artifact@v2
        with:
          name: bandit-report
          path: $(pwd)/report/dependency-check-report.html
#odc-reports
  security-bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Run bandit on Superset code
        run: |
          pip install bandit 
          bandit -r ${{ github.workspace }}/superset

  pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools
          sudo apt-get update
          sudo apt-get install -y python3-distutils

      - uses: pypa/gh-action-pip-audit@v1.0.8
